### ISSUE TITLE
Categories are missing from appstream data

### ISSUE THREAD

**Issue by bbhtt** [flathub/me.iepure.devtoolbox#9]
https://github.com/aleiepure/devtoolbox/blob/e1a5f1d2d2f1da3e2d775bf4451dbc3ec1168b08/data/me.iepure.devtoolbox.desktop.in.in#L12

This is due to the desktop file having a low quality category that is filtered by appstream
Please define a proper category from https://specifications.freedesktop.org/menu-spec/latest/apa.html

**Comment by Zishan-Rahman** [comment]
This has been addressed by #11, which has recently been merged and just been pushed to Flathub. The Flatpak's desktop file now has a `Development` category. This issue can be closed now :+1:
